### ISSUE TITLE
Gradle sync error in android studio

### ISSUE THREAD

**Issue by tyczj** [flavienlaurent/discrollview#2]
when I put 

```
compile 'com.github.flavienlaurent.discrollview:library:0.0.2@aar'
```

in my build.gradle file with my other libraries I get an error during the gradle sync saying

"Could not find com.github.flavienlaurent.discrollview:library:0.0.2."

any idea?

**Comment by flavienlaurent** [comment]
Sorry for that. Juste forgot to release it on maven central ... ^^

It's done now ;)
