### ISSUE TITLE
Parallax Scrolling in Child layout

### ISSUE THREAD

**Issue by tyczj** [flavienlaurent/discrollview#3]
Lets say I have a Child Layout that implements Discrollvable and I set a background image for that layout, Is there a way to implement a parallax scroll effect in that view similar to how this site looks for example? http://www.soyuzcoffee.com/ru/home

**Comment by flavienlaurent** [comment]
You can use the ratio value in the onDiscrollve method to make a parallax scroll effect. It must be implemented by translating the image matrix thanks to the discrollve ratio value.
