### ISSUE TITLE
listviewscroll

### ISSUE THREAD

**Issue by loveyouandroid** [flavienlaurent/discrollview#6]
hello
i tried to make it work on listview but i could not
1- i create a listview adapter
2- i create a single row layout and give the for example title textview  discrollve:discrollve_translation="fromRight" 
but it not works you know
instead of using scrolview and put the childs one by one 
i want it to be a listview that it can loads many data.

my english is too poor can you please help me with this one and change my life? beg you

**Comment by flavienlaurent** [comment]
It doesn't work with listviews.
